# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LagrangeInterp <- function(x, y, xy, zs) {
    .Call('_dnipm_LagrangeInterp', PACKAGE = 'dnipm', x, y, xy, zs)
}

