# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bilinearInterp <- function(xy, xs, ys, zs) {
    .Call('_dnipm_bilinearInterp', PACKAGE = 'dnipm', xy, xs, ys, zs)
}

lagrangeInterp <- function(xy, xys, zs) {
    .Call('_dnipm_lagrangeInterp', PACKAGE = 'dnipm', xy, xys, zs)
}

